# Generated by Django 4.1.7 on 2023-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('cpf_aluno', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('sp', 'São Paulo'), ('mg', 'Minas Gerais')], default='sp', max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('turma', models.CharField(choices=[('turma_a', 'Turma A'), ('turma_b', 'Turma B')], default='turma_a', max_length=10)),
            ],
        ),
    ]
